name: Build CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - run: go version
      - name: Install GOMOD
        run: |
          git clone https://github.com/FlowerLab/sorbifolia
          cd sorbifolia
          go install go.x2ox.com/sorbifolia/gomod/gomod
      - name: Build
        run: |
          gomod
          echo "go.x2ox.com" > go.x2ox.com/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.3.0
        with:
          branch: gh-pages
          folder: go.x2ox.com
          force: false
