name: GOMOD Build CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "20 22 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - run: go version
      - name: Install GOMOD
        run: go install go.x2ox.com/sorbifolia/gomod/gomod@v0.0.0-20220415111418-11283f51cc00
      - name: Build
        run: gomod -f data.json
      - name: Add public resource
        run: |
          cp -r public/* go.x2ox.com
      - name: Install Sitemap Generator
        run: go install go.x2ox.com/sorbifolia/sitemap/sitemap-generator@v0.0.0-20220420102858-f1db7131b5a2
      - name: Generate Sitemap
        run: |
          sitemap-generator -f sitemap.config.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: go.x2ox.com
          cname: go.x2ox.com
          keep_files: true
